//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW1B.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW1B.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricia Jordan	57	94988
        ///Diana Sellers	51	67999
        ///Aaron Price	32	67143
        ///Carla Warren	72	77873
        ///Mr. Kent Perry	47	70194
        ///Karen Lee	23	57908
        ///Douglas Nelson	53	89714
        ///Douglas Ortiz	42	68010
        ///Jeffrey Ortiz	46	98724
        ///Annette Dawson	54	10405
        ///Carmen Duarte	69	24830
        ///Christine Monroe	87	83362
        ///David Shaw	84	32966
        ///Jade Wells	22	41548
        ///Dawn Anderson	51	45551
        ///Mark Robinson	69	62767
        ///Mrs. Sarah Molina	22	58698
        ///Melanie Mendez	39	32225
        ///Austin Daniels	73	94734
        ///Andrew Scott	48	98034
        ///John Wang	42	96773
        ///Robert Foster	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dummydata {
            get {
                return ResourceManager.GetString("dummydata", resourceCulture);
            }
        }
    }
}
